### ISSUE TITLE
April Fools joke actually benefits this extension because...

### ISSUE THREAD

**Issue by Ralkage** [ReFlar/nightmode#1]
https://github.com/clarkwinkelmann/flarum-ext-high-contrast

@Shahiem you can basically tweak this to allow Night Mode with ease 😂

The setting in that joke extension for April Fools can make Night Mode user enabled.

**Comment by Shahiem** [comment]
That's a cool plugin, but you can't enable the actual "dark theme" with that. And I'm planning to make this feature also for guests not only for users :)

**Comment by Ralkage** [comment]
Ahhh, that works too! I figured this would be easier since Clark is basically giving us the okay to use his source code. Lets see what you got then ;)

**Comment by Sinamics** [comment]
awesome if this can be tuned into a dark mode extension... love the idea.

**Comment by Shahiem** [comment]
It's easy, I agree but not what I had in mind. I thought about doing the same; adding a class to the body and add a dark background color. But that's not really the "night mode", it takes more time to add classes to the elements to change it to dark.
