### ISSUE TITLE
Localization issue

### ISSUE THREAD

**Issue by hexicans** [ReFlar/nightmode#13]
hello,

There is a problem with traduction or... ? 

> http://j.axel-hauguel.fr/18122018-23:34:45.png

**Comment by CDK2020** [comment]
I can't view your screenshot, please repost it

**Comment by datitisev** [comment]
![image](https://user-images.githubusercontent.com/6401250/51143562-d7316400-181c-11e9-9bdd-f65e19374993.png)

**Comment by datitisev** [comment]
@hexicans Try hard-refreshing the page and/or clearing the Flarum cache through the dashboard in the admin interface.

**Comment by Ralkage** [comment]
Hi @hexicans, is this still an issue?

If the above solution does not fix your problem, please let us know.

Otherwise, we will be closing this issue in 48 hours.

**Comment by hexicans** [comment]
Hello,

I fixed myself in the evening of my post, I did not try your solution suddenly :( Thanks anyway, I hope that it goes the others.
