### ISSUE TITLE
Beta 9 Compatibility Status

### ISSUE THREAD

**Issue by JoshStrobl** [ReFlar/nightmode#22]
### Instructions (MUST READ FIRST)

Before we can address your issues and concerns with the behavior of our work, we require every bit of detail from you to the fullest extent of this form. If this form is not properly filled out to it's entirity, we, ReFlar, reserve the right to close your issue due to lack of information thereof as well as not following instructions.

* [x] By agreeing to these terms, you can simply leave this checkbox checked.

### Description

What is the current status of beta 9 compatibility? I'm inquiring as this hasn't seen any updates since December and the [Solus](https://getsol.us) project is currently evaluating the viability of updating from beta 8.2 within negatively impacting our users, so I'm wanting to ensure we don't have any blockers to doing so.

Thanks!

**Comment by datitisev** [comment]
@JoshStrobl Most extensions should work just fine in beta 9 if they support beta 8.
