### ISSUE TITLE
NightMode white background after opening the link

### ISSUE THREAD

**Issue by youhosi** [ReFlar/nightmode#4]
* Can you reproduce this problem in debug mode? Now I can not
* Are you running the latest version of this extension? So newest, 0.1.3
* Is your Flarum up-to-date? Yes, it is current

### Description

When I open a link in a discussion that opens a new tab, the background instead of being dark appears white.

### Screenshot

https://imgur.com/a/A7iuYpa

### Technical Details

- Version of Flarum: 0.1.0-beta.7
- Version of extension: 0.1.3
- Website URL where the bug is visible: https://forum.oxidepolska.eu
- The webserver you are running: nginx/1.13.12
- PHP version: PHP 7.1.17
- Hosted environment: VPS

### Output info (ext)

EXT flarum-akismet v0.1.0-beta.6
EXT flarum-approval v0.1.0-beta.7
EXT zaptech-cookie-consent 0.1.0-beta3
EXT flarum-emoji v0.1.0-beta.6
EXT clarkwinkelmann-emojionearea 0.1.2
EXT flarum-english v0.1.0-beta.7
EXT flarum-flags v0.1.0-beta.7
EXT flarum-auth-github v0.1.0-beta.6
EXT sijad-recaptcha 0.0.2
EXT sijad-links 0.1.0-beta.6
EXT flarum-lock v0.1.0-beta.7
EXT flarum-markdown v0.1.0-beta.5
EXT ganuonglachanh-markdown-editor 0.9
EXT dogsports-pipetables 1.0.8
EXT flarum-mentions v0.1.0-beta.7
EXT antoinefr-money 0.5.0
EXT sijad-pages 0.1.0-beta.3
EXT wiseclock-profile-image-crop 0.1.1
EXT flarum-pusher v0.1.0-beta.6
EXT reflar-nightmode 0.1.3
EXT terabin-sitemap v1.0.2-beta.2
EXT sijad-auth-steam 0.1.10
EXT flarum-sticky v0.1.0-beta.7
EXT flarum-subscriptions v0.1.0-beta.6
EXT flarum-suspend v0.1.0-beta.7
EXT flarum-tags v0.1.0-beta.8

**Comment by datitisev** [comment]
Hm, I cannot reproduce this, tried with debug mode on & off. 🤔

**Comment by Shahiem** [comment]
It is not happening with my forum. So, could you clear your cache?
```
php flarum cache:clear
```

**Comment by youhosi** [comment]
I have cleared, but the problem still occurs.

**Comment by datitisev** [comment]
So, let me get confirm the steps:

1. Open discussion that contains link to another discussion
2. Click discussion link (which opens in another tab)
3. The tab opened will have day mode even though user has preferences set to dark mode

Correct?

**Comment by youhosi** [comment]
Exactly.

https://streamable.com/vnvds

**Comment by datitisev** [comment]
Still can't reproduce.

![2018-05-12 17-25-01](https://user-images.githubusercontent.com/6401250/39961706-00b61008-560a-11e8-9f3e-ee7b5b2c60ac.gif)

Are there any errors in the javascript console (F12)? The script may be failing to add the `.dark` class to the body for some reason.

**Comment by Shahiem** [comment]
@datitisev  Check your /tags page. It's not working on the tags page and the discussion page. Its weird that the discussion page works well on my local flarum.

**Comment by datitisev** [comment]
As far as I can see, it only shows the white theme on the tags page and the admin page for me (and I assume the admin page is supposed to have the white theme).

**Comment by youhosi** [comment]
So the administrator's site has a white theme.
Screenshot: https://imgur.com/a/3CNHqX0

Maybe I install a flarum from scratch? Only then what about the database?

**Comment by Shahiem** [comment]
Tag page is fixed now. Now I have to think how to fix the discussion page. (I have a idea how, but I'm not sure if that will work for you guys)

@youhosi  You could install a flarum from scratch if you want.

**Comment by datitisev** [comment]
@youhosi You shouldn't need to reinstall Flarum, this is an issue with the extension most likely.

Check the JavaScript console in the tab with the white background, see if it has any errors.

**Comment by youhosi** [comment]
@datitisev  There are no errors in the console

**Comment by youhosi** [comment]
When installing the flarum from scratch, I came to the conclusion that the error causes plugin "flagrow/upload"

**Comment by CDK2020** [comment]
Can you tell us how you came to that conclusion so we may fix the potential incompatibility?

**Comment by youhosi** [comment]
At the very beginning of the extension installation, I have been using the night mode, other extensions did not cause problems, when I made the sending of files the problem occurred.

**Comment by datitisev** [comment]
I cannot reproduce this, and the image in the second discussion was uploaded using flagrow/upload, and flagrow/upload is enabled.

![2018-05-13 15-44-24](https://user-images.githubusercontent.com/6401250/39971156-ad0d8c18-56c4-11e8-9255-e5e24dcdd6b4.gif)

**Comment by datitisev** [comment]
@youhosi Can you maybe create a gif showing the bug?

**Comment by Shahiem** [comment]
We've made some changes in our code. Could you try this and see if this solves the problem?

Please, run:


```
composer require reflar/nightmode:@dev
```

**Comment by youhosi** [comment]
`flarum@strona:~/flarum$ composer require reflar/nightmode:@dev
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Package http-interop/http-middleware is abandoned, you should avoid using it. Use http-interop/http-server-middleware instead.
Writing lock file
Generating autoload files
flarum@strona:~/flarum$`

When I'm browsing discussions:

https://im4.ezgif.com/tmp/ezgif-4-87e3124a7c.gif

When I browse the pages

https://im4.ezgif.com/tmp/ezgif-4-30661c4c82.gif

**Comment by CDK2020** [comment]
Try this:

Completely remove nightmode `composer remove reflar/nightmode`

Then install it again: `composer require reflar/nightmode *@dev`

**Comment by youhosi** [comment]
@Shahiem Nie przyniosło to żadnych zmian :(

**Comment by CDK2020** [comment]
It appears you still have the old code, we tagged **0.1.4** please try running `composer update reflar/nightmode` and see if that fixes it

**Comment by youhosi** [comment]
I'm getting 1.0.3 when installing dev
```
flarum@strona:~/flarum$ composer require reflar/nightmode *@dev
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing reflar/nightmode (0.1.3): Downloading (100%)         

```

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
```

**Comment by datitisev** [comment]
@youhosi Run `composer require reflar/nightmode 0.1.4`

**Comment by youhosi** [comment]
```
  [InvalidArgumentException]                                           
  Could not find package reflar/nightmode in a version matching 0.1.4
```

**Comment by datitisev** [comment]
@youhosi Try again, just run `composer update reflar/nightmode`, our apologies, Packagist wasn't updated.

**Comment by youhosi** [comment]
Its works!!!! I love it!
