### ISSUE TITLE
Stickied Posts text still appears black

### ISSUE THREAD

**Issue by edxtech** [ReFlar/nightmode#9]
### Description

The title of Sticked posts is black in night mode.

### Steps to Reproduce

1. Turn on night mode
2. Make a post
3. Sticky it

**Expected Behavior:** Text looks like any other post title

**Actual Behavior:** 
![image](https://user-images.githubusercontent.com/28843864/41004962-8c160efc-6913-11e8-81e5-3837430a3548.png)

Latest

**Comment by Ralkage** [comment]
The solution for this is simple, remove or adjust any modifications you have to the Custom CSS/LESS section on the Appearance tab in your Admin CP. Out of the box, ReFlar Nightmode does not look like or should look like what you have in your screenshot above. If you have any customizations you must keep, please accommodate for Nightmode as well.
